// Export pages
export '/pages/min_k_y_c/add_onsmin_k_y_c/add_onsmin_k_y_c_widget.dart'
    show AddOnsminKYCWidget;
export '/pages/min_k_y_c/user_detailsmin_k_y_c/user_detailsmin_k_y_c_widget.dart'
    show UserDetailsminKYCWidget;
export '/pages/min_k_y_c/confirm_paymentmin_k_y_c/confirm_paymentmin_k_y_c_widget.dart'
    show ConfirmPaymentminKYCWidget;
export '/pages/min_k_y_c/activate_tagmin_k_y_c/activate_tagmin_k_y_c_widget.dart'
    show ActivateTagminKYCWidget;
export '/pages/biometric/user_details_biometric/user_details_biometric_widget.dart'
    show UserDetailsBiometricWidget;
export '/pages/min_k_y_c/customer_detailsmin_k_y_c/customer_detailsmin_k_y_c_widget.dart'
    show CustomerDetailsminKYCWidget;
export '/pages/chassis/customer_details_chassis/customer_details_chassis_widget.dart'
    show CustomerDetailsChassisWidget;
export '/pages/biometric/customer_details_biometric/customer_details_biometric_widget.dart'
    show CustomerDetailsBiometricWidget;
export '/pages/chassis/add_ons_chassis/add_ons_chassis_widget.dart'
    show AddOnsChassisWidget;
export '/pages/biometric/confirm_payment_biometric/confirm_payment_biometric_widget.dart'
    show ConfirmPaymentBiometricWidget;
export '/pages/biometric/add_on_biometric/add_on_biometric_widget.dart'
    show AddOnBiometricWidget;
export '/pages/chassis/activate_tag_chassis/activate_tag_chassis_widget.dart'
    show ActivateTagChassisWidget;
export '/pages/biometric/activate_tag_biometric/activate_tag_biometric_widget.dart'
    show ActivateTagBiometricWidget;
export '/pages/chassis/confirm_payment_chassis/confirm_payment_chassis_widget.dart'
    show ConfirmPaymentChassisWidget;
export '/pages/chassis/user_details_chassis/user_details_chassis_widget.dart'
    show UserDetailsChassisWidget;
export '/pages/chassis_to_v_r_n_b_c/customer_details_chassisto_v_r_n_b_c/customer_details_chassisto_v_r_n_b_c_widget.dart'
    show CustomerDetailsChassistoVRNBCWidget;
export '/pages/chassis_v_r_nto_v_r_n_o_p_sflow/customer_details_chassis_v_r_nto_v_r_n_o_p_s/customer_details_chassis_v_r_nto_v_r_n_o_p_s_widget.dart'
    show CustomerDetailsChassisVRNtoVRNOPSWidget;
export '/pages/consent/consent/consent_widget.dart' show ConsentWidget;
export '/pages/chassis_to_v_r_n_o_p_s/customer_details_chassisto_v_r_n_o_p_s/customer_details_chassisto_v_r_n_o_p_s_widget.dart'
    show CustomerDetailsChassistoVRNOPSWidget;
export '/pages/min_k_y_c_v_c4_noncommercial/user_detailsmin_k_y_c_v_c4_nc/user_detailsmin_k_y_c_v_c4_nc_widget.dart'
    show UserDetailsminKYCVC4NcWidget;
export '/pages/min_k_y_c_v_c4_noncommercial/customer_detailsmin_v_c4_nc/customer_detailsmin_v_c4_nc_widget.dart'
    show CustomerDetailsminVC4NcWidget;
export '/pages/tag_replacement/tagreplacement/tagreplacement_widget.dart'
    show TagreplacementWidget;
export '/pages/manual_k_y_c/manual_k_y_c_l_l_p/upload_document_manual_k_y_c_l_l_p/upload_document_manual_k_y_c_l_l_p_widget.dart'
    show UploadDocumentManualKYCLLPWidget;
export '/pages/manual_k_y_c/manual_k_y_c_partnership/upload_document_manual_k_y_c_partnership/upload_document_manual_k_y_c_partnership_widget.dart'
    show UploadDocumentManualKYCPartnershipWidget;
export '/pages/manual_k_y_c/manual_k_y_c_proprietorship/upload_document_manual_k_y_c_proprietorship/upload_document_manual_k_y_c_proprietorship_widget.dart'
    show UploadDocumentManualKYCProprietorshipWidget;
export '/pages/manual_k_y_c/manual_k_y_c_company_ltdand_pvt_ltd/upload_document_manual_k_y_c_ltdand_pvt_ltd/upload_document_manual_k_y_c_ltdand_pvt_ltd_widget.dart'
    show UploadDocumentManualKYCLtdandPvtLtdWidget;
export '/pages/manual_k_y_c/manual_k_y_c_issuance_journey/activate_tag_man_k_y_c_i_j/activate_tag_man_k_y_c_i_j_widget.dart'
    show ActivateTagManKYCIJWidget;
export '/pages/manual_k_y_c/manual_k_y_c_issuance_journey/confirm_payment_man_k_y_c_i_j/confirm_payment_man_k_y_c_i_j_widget.dart'
    show ConfirmPaymentManKYCIJWidget;
export '/pages/manual_k_y_c/manual_k_y_c_issuance_journey/add_on_man_k_y_c_i_j/add_on_man_k_y_c_i_j_widget.dart'
    show AddOnManKYCIJWidget;
export '/pages/manual_k_y_c/manual_k_y_c_issuance_journey/customer_details_man_k_y_c_i_j/customer_details_man_k_y_c_i_j_widget.dart'
    show CustomerDetailsManKYCIJWidget;
export '/pages/manual_k_y_c/manual_k_y_c_status_check/customer_details_man_k_y_c_s_c/customer_details_man_k_y_c_s_c_widget.dart'
    show CustomerDetailsManKYCSCWidget;
export '/pages/manual_k_y_c/manual_k_y_c/manual_k_y_c_widget.dart'
    show ManualKYCWidget;
export '/pages/min_k_y_c/vehicle_details/vehicle_details_widget.dart'
    show VehicleDetailsWidget;
export '/pages/min_k_y_c/customer_details_man_k_y_c_e_t_b_c_s/customer_details_man_k_y_c_e_t_b_c_s_widget.dart'
    show CustomerDetailsManKYCETBCSWidget;
export '/pages/chassis/customer_details_chassis_copy/customer_details_chassis_copy_widget.dart'
    show CustomerDetailsChassisCopyWidget;
export '/test_page/test_page_widget.dart' show TestPageWidget;
export '/test_web_integration/test_web_integration_widget.dart'
    show TestWebIntegrationWidget;
